theme: jekyll-theme-cayman
title: "The Mueller Report E-Book"
description: "A reflowable e-book version of the 2017-2019 Special Counsel investigation report."
show_downloads: true

github:
  mobi_url: "https://github.com/jonscheiding/mueller-report-ebook/releases/download/1.3/mueller-ebook.mobi"
  epub_url: "https://github.com/jonscheiding/mueller-report-ebook/releases/download/1.3/mueller-ebook.epub"
